<?php

/**
 * @file
 *  Let users add private annotations to nodes.
 *
 * Adds a text field when a node is displayed
 * so that authenticated users may take notes.
 */


 /**
  * Implements hook_menu().
  */
  function annotate_menu() {
    $items['admin/config/annotate'] = [
      'title' => 'Node annotation',
      'description' => 'Adjust node annotation options.',
      'position' => 'right',
      'weight' => -5,
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => ['administer site configuration'],
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
    ];

    $items['admin/config/annotate/settings'] = [
      'title' => 'Annotation settings',
      'description' => 'Change how annotations behave.',
      'page callback' => 'drupal_get_form',
      'page arguments' => ['annotate_admin_settings'],
      'access arguments' => ['administer site configuration'],
      'type' => MENU_NORMAL_ITEM,
      'file' => 'annotate.admin.inc',
    ];

    return $items;
  }
